Migrate nationality_j_s for NDS
hitobito/hitobito_youth pull request #23
Opened 2023-01-26 16:00 UTC by TheWalkingLeek

Closes: https://github.com/hitobito/hitobito/issues/1961

2023-01-26 16:27 UTC, kronn requested changes
Grundsätzlich cool, hat noch ein paar kleinere Ecken.

2023-01-26 16:27 UTC, kronn commented on app/views/event/participation_contact_datas/_fields_youth.html.haml
> +                                  :to_s, Proc.new { |n| t(".nationality_j_s.#{n}") },
Ich fände hier den absoluten Pfad zur Modelattribut-Übersetzung besser. Ich sehe nicht, warum man es für den View anders machen möchte und will andererseits Änderungen wirklich zentral machen.

```suggestion
                                  :to_s, Proc.new { |n| t("activerecord.attributes.person.nationalities_j_s.#{n}") },
```

2023-01-26 16:27 UTC, kronn commented on app/views/people/_fields_youth.html.haml
> +                                :to_s, Proc.new { |n| t(".nationality_j_s.#{n}") },
Gleichermassen:

```suggestion
                                :to_s, Proc.new { |n| t("activerecord.attributes.person.nationalities_j_s.#{n}") },
```

2023-01-26 16:27 UTC, kronn commented on config/locales/models.youth.fr.yml
> +          ANDERE: AUTRE
Hier bitte noch daran denken, die direkten Übersetzungen zu transifex zu pushen. Standardmässig werden nur die deutschen Versionen als Quellen hochgeladen, der Rest wird bei Releases mit dem Stand bei transifex überschrieben.

2023-01-26 16:27 UTC, kronn commented on config/locales/views.youth.de.yml
> +        ANDERE: ANDERE
Braucht es nicht, wenn immer die Übersetzung aus den Models genommen wird. Gilt für alles in den `views.youth.*.yml`-Dateien

2023-01-26 16:27 UTC, kronn commented on db/migrate/20230126155336_migrate_nationality_to_new_nds.rb
> +    SQL
:heart_eyes_cat:

2023-01-26 17:03 UTC, carlobeltrame requested changes
Es ist etwas verdächtig, dass du keinen Test anpassen musstest für die Änderung die sich eigentlich im NDS Kurs- und Lager-Export manifestieren müsste. Könntest du noch kontrollieren ob der Export jetzt so aussieht wie gewünscht, und gegebenenfalls noch einen Test dafür ergänzen?

2023-01-27 06:52 UTC, TheWalkingLeek commented
Das mit dem Spec hab ich auch gedacht.. Letztendlich ist es aber beim Export einfach ein: "Person mit nationality ANDERE erstellen -> Export exportiert ANDERE"
Der Export macht nichts mit den Daten sondern exportiert einfach was in der DB ist. Daher die Tests, dass das in der DB stimmt :)
Aber just to be sure kann ich gut noch einen Spec machen. Lieber zu viel statt zu wenig

2023-01-30 11:50 UTC, kronn approved these changes

2023-01-30 11:51 UTC, merged